version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 042501517500.dkr.ecr.ap-south-1.amazonaws.com

  build:
  commands:
    - docker build -t java-app -f app/Dockerfile app/

  post_build:
    commands:
      - docker push 042501517500.dkr.ecr.ap-south-1.amazonaws.com/java-app
